### ISSUE TITLE
ArgumentError for folded tag

### ISSUE THREAD

**Issue by takahashim** [amatsuda/himl#3]
```
$ ./bin/console 
irb(main):001:0> parser=Himl::Parser.new
=> #<Himl::Parser:0x00007fe9531f0240>
irb(main):002:0> parser.call(<<EOB)
irb(main):003:1" <div
irb(main):004:1"   class="c1">
irb(main):005:1" EOB
Traceback (most recent call last):
        7: from ./bin/console:14:in `<main>'
        6: from (irb):2
        5: from /Users/maki/git/himl/lib/himl/parser.rb:155:in `call'
        4: from /Users/maki/git/himl/lib/himl/parser.rb:171:in `parse_template'
        3: from /Users/maki/git/himl/lib/himl/parser.rb:122:in `close_document!'
        2: from /Users/maki/git/himl/lib/himl/parser.rb:143:in `close_tags'
        1: from /Users/maki/git/himl/lib/himl/parser.rb:143:in `<='
ArgumentError (comparison of Integer with nil failed)
```

Should it be `SyntaxError`?  Or parser's bug?

**Comment by amatsuda** [comment]
Wow, this should be a parser bug.
This case just wasn't considered...
